version: '3.8'

services:
  api_roles:
    container_name: backend_roles
    build: .
    ports:
      - 3005:3005
    env_file: .env
    volumes: 
      - ./:/code
      - node_modules:/code/node_modules
    networks:
      - backend_roles
      - siged_backend
    depends_on: 
      - db_roles

  db_roles:
    container_name: db_roles
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: api_roles
      MONGO_INITDB_ROOT_PASSWORD: roles_password
      MONGO_INITDB_DATABASE: api_roles_db
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
    networks: 
      - backend_roles

volumes:
  node_modules:
  mongodb:

networks:
  backend_roles:
  siged_backend:
      external: false